doctrine_migrations:
    em: mysql
    migrations_paths:
        # namespace is arbitrary but should be different from App\Migrations
        # as migrations classes should NOT be autoloaded
        'DoctrineMigrations': '%kernel.project_dir%/migrations/mysql'
        'ClickHouseMigration': '%kernel.project_dir%/migrations/clickhouse'
    enable_profiler: '%kernel.debug%'
    factories:
        'Doctrine\Migrations\Version\MigrationFactory': 'App\Doctrine\ClickHouse\ClickHouseMigrationFactory'

