version: "3"

services:
    db:
        image: mysql:8.0.23
        platform: linux/x86_64
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - "db_app:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports:
            - 3306:3306
        networks:
            - symfony
    php:
        build:
            context: ./php
            args:
                TIMEZONE: ${TIMEZONE}
        volumes:
            - ../:/var/www/symfony/
        networks:
            - symfony
    nginx:
        build:
            context: ./nginx
        volumes:
            - ../:/var/www/symfony/
        ports:
            - 80:80
        networks:
            - symfony
        env_file:
            - .env.nginx.local

    clickhouse_server:
        image: yandex/clickhouse-server
        ports:
            - "8123:8123"
            - "9006:9000"
            - "9009:9009"
        ulimits:
            nproc: 65535
            nofile:
                soft: 262144
                hard: 262144
        volumes:
            - ../clickhouse_data:/var/lib/clickhouse
        restart: always
        networks:
            - symfony

volumes:
    symfony_dockerized_app_sync:
        external: true
    db_app:

networks:
    symfony:
